name: ci
on: [push]
jobs:
  tests:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-22.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install npm dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Launch korojscommands
        run: node lib/index.js
      - name: Launch korojscommands
        run: node lib/index.js --version
      - name: linter readme.md
        run: npm run lint:markdown