name: ci
on: [push]
jobs:
  tests:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-22.04]
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
            submodules: recursive
      - name: Cache npm packages
        id: npm-cache
        uses: actions/cache@v4
        with:
            path: node_modules
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-node-
      - name: Install npm dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Build
        run: npm run build
      - name: Launch korojscommands
        run: node lib/index.js
        continue-on-error: true
      - name: Check global-command
        run: node lib/index.js global-command
      - name: Check version
        run: node lib/index.js --version
      - name: linter readme.md
        run: npm run lint:markdown